server {
    listen $PORT;
    server_name _;
    root /usr/share/nginx/html;
    index guia-pratico-direito-transito.html;

    location ~ ^(/.+\.html)/$ {
        return 301 $scheme://$http_host$1$is_args$args;
    }

    location / {
        try_files $uri $uri/ /guia-pratico-direito-transito.html;
    }
}
