server {
    listen $PORT;
    server_name _;
    root /usr/share/nginx/html;
    index guia-pratico-direito-transito.html;

    rewrite ^/(.*)/$ /$1 permanent;

    location / {
        try_files $uri $uri/ /guia-pratico-direito-transito.html;
    }
}
