server {
    listen $PORT;
    server_name _;
    root /usr/share/nginx/html;
    index guia-pratico-direito-transito.html;

    location / {
        rewrite ^/(.*)/$ /$1 last;
        try_files $uri $uri/ /guia-pratico-direito-transito.html;
    }
}
